name: Run Node.js Bot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual start
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start bot
        run: node index.js # Change index.js to your bot's entry file
